name: ST-CustomMenu
main: net.starly.custommenu.CustomMenu
author: Starly Team
website: http://starly.kr/

description: CustomMenu Plugin.

depend: [ NBTAPI ]

version: 1.1
api-version: 1.13

commands:
  custom-menu:
    description: 커스텀 메뉴 명령어
    aliases: [ menu, 커스텀메뉴, 메뉴 ]