name: ST-CustomMenu
main: net.starly.menu.CustomMenu
author: Starly Team
website: http://starly.kr/

description: CustomMenu Plugin.

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

commands:

  custom-menu:
    description: 커스텀 메뉴 명령어
    aliases: [ menu, cm, 커스텀메뉴, 메뉴 ]